spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/demo
    username: demo
    password: demo1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 개발 중에는 update, 운영에서는 validate 권장
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: my-secret-key-very-strong-and-long
  expiration: 3600000 # 1시간 (ms)